### ISSUE TITLE
Cannot find ggml file

### ISSUE THREAD

**Issue by AIbottesting** [ngxson/alpaca.cpp-webui#2]
This looks so good. I wish I could get it to work. 
I'm running Windows 10 with docker and app store WSL.
I get this error through the web browser after loading through command line:

<Cannot find ggml model file or executable file under {YOUR_PROJECT_DIRECTORY}/bin

Please follow this guide to download the model:
https://github.com/ngxson/alpaca.cpp-webui#how-to-use

Then, make sure that these paths exist:
/app/bin/chat
/app/bin/ggml-alpaca-7b-q4.bin>

I created a folder named app with bin in it (to match the path above) and it still didn't work. I have ggml-alpaca-7b-q4.bin and chat in both a folder  /bin and /app/bin just to cover my bases... but no luck.

**Comment by ngxson** [comment]
The model should be placed here: https://github.com/ngxson/alpaca.cpp-webui/tree/master/bin
Not your system `/bin` or `/app/bin`, just `{YOUR_PROJECT_DIRECTORY}/bin`

Alternatively, you can try without docker. I recommend using ubuntu 22 as base OS, then using this command to install nodejs 18:

```
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get install nodejs
```

**Comment by AIbottesting** [comment]
Yes that is the /bin folder it is in: {YOUR_PROJECT_DIRECTORY}/bin
It's okay. I'll try Linux some other day. Thanks for the fast response.
